openapi: 3.0.0
info:
  title: Todo API
  version: 1.0.0
  description: API for todos
servers:
  - url: http://localhost:3000/api
paths:
  /tasks:
    get:
      summary: Get all todos
      responses:
        200:
          description: A list of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
    post:
      summary: Create a new todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoInput'
      responses:
        201:
          description: The created todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
  /tasks/{id}:
    put:
      summary: Update a todo by ID
      parameters:
        - in: path
          name: id
          required: true
          description: The ID of the todo to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoInput'
      responses:
        200:
          description: The updated todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
    delete:
      summary: Delete a todo by ID
      parameters:
        - in: path
          name: id
          required: true
          description: The ID of the todo to delete
          schema:
            type: string
      responses:
        204:
          description: Todo successfully deleted

components:
  schemas:
    Todo:
      type: object
      properties:
        _id:
          type: string
          description: The unique identifier for the todo
        title:
          type: string
          description: The title of the todo
        description:
          type: string
          description: A detailed description of the todo
        completed:
          type: boolean
          description: Indicates whether the todo is completed
        createdAt:
          type: string
          format: date-time
          description: The date and time when the todo was created
        updatedAt:
          type: string
          format: date-time
          description: The date and time when the todo was last updated
    TodoInput:
      type: object
      properties:
        title:
          type: string
          description: The title of the todo
        description:
          type: string
          description: A detailed description of the todo
        completed:
          type: boolean
          description: Indicates whether the todo is completed
      required:
        - title
